#!/usr/bin/env bash
# scripts/update-versions.sh
# Auto-generates VERSIONS from current submodule states.
# Run this after updating any submodule.
#
# Usage:
#   bash scripts/update-versions.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/VERSIONS"

cat > "$OUT" << 'EOF'
# VERSIONS - XiangShan AI Environment Component Versions
#
# Auto-generated by scripts/update-versions.sh
# Do NOT edit manually. Run: bash scripts/update-versions.sh
#
# Format:
#   <submodule-path>  <commit>  <date>  <branch/tag>  <remote-url>
EOF

echo "" >> "$OUT"
printf "# Generated: %s\n\n" "$(date -u '+%Y-%m-%d %H:%M UTC')" >> "$OUT"
printf "%-30s  %-42s  %-25s  %-30s  %s\n" \
    "# COMPONENT" "COMMIT" "DATE" "BRANCH/TAG" "URL" >> "$OUT"
printf "%-30s  %-42s  %-25s  %-30s  %s\n" \
    "# ---------" "------" "----" "----------" "---" >> "$OUT"

cd "$ROOT"

git submodule foreach --quiet '
    commit=$(git rev-parse HEAD)
    date=$(git log -1 --format="%ci" HEAD)
    branch=$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --exact-match HEAD 2>/dev/null || echo "(detached)")
    url=$(git remote get-url origin 2>/dev/null || echo "local")
    printf "%-30s  %-42s  %-25s  %-30s  %s\n" "$name" "$commit" "$date" "$branch" "$url"
' >> "$OUT"

echo ""
echo "[versions] VERSIONS updated:"
grep -v "^#" "$OUT" | grep -v "^$"
